spring.application.name=awslocalS3
server.port=8080

# Floci Local AWS
aws.s3.endpoint=http://localhost:4566
aws.region=us-east-1
aws.accessKey=test
aws.secretKey=test
cdn.url=https://uniformed-credit-overpay.ngrok-free.dev
# Bucket Name
aws.s3.bucket=media-bucket

# Max Upload Size
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB